apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 405072334377.dkr.ecr.us-east-1.amazonaws.com/simplebank:bc20f7b9f554ca7124dac8ca70deb2327d140fe5
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
